version: 2.1

executors:
  custom-executor:
    docker:
      - image: circleci/node:lts-browsers

jobs:
  build:
    executor: custom-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: Installing local dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /home/circleci/project
          paths: 
            - app
            - src
            - node_modules

  test:
    executor: custom-executor
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Test
          command: echo "Run some tests..."

  lint:
    executor: custom-executor
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Lint
          command: echo "Linting..."

  deploy:
    executor: custom-executor
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: SLS deploy
          command: | 
            cd src/
            ./node_modules/.bin/serverless deploy -v

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint: 
          requires:
            - build
      - deploy:
          requires: 
            - build
            - test
          filters:
            branches:
              only: master
