service:
  name: basic-serverless-ci-cd
app: serverless-ci-cd


custom:
  customDomain:
    domainName: 'api.anhydride.info'
    basePath: api
    certificateName: '*.anhydride.info'
    #createRoute53Record: true
    securityPolicy: tls_1_2
    certificateArn: ${ssm:/AllEnvironments/certificateARN}

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  # If you have multiple accounts use profile
  profile: serverless-admin
  logs:
    restApi: true

functions:
  getJobDetails:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /